### ISSUE TITLE
Outdated Login Section in Lab 1

### ISSUE THREAD

**Issue by rdrake** [uoitsci/pi-labs#2]
The instructions for lab 1 instruct students to log in via text mode using the username `pi` and the password `raspberry`.  This section should be updated to reflect the fact that students use their SCIENCE.UOIT.CA accounts to log in and the Pi boots to the graphical login screen instead of text.

**Comment by rdrake** [comment]
The lab also makes references to `$HOME=/home/pi`.  This should be updated to `$HOME=/home/$(whoami)`.

**Comment by randyfortier** [comment]
Thanks.  Updated on GitHub.

**Comment by randyfortier** [comment]
Does the web server pull the changes automatically after a delay?

Do these students know their science.uoit.ca credentials?

**Comment by rdrake** [comment]
Fixed in 29da607.
